# This workflow will do a clean install of node dependencies, build the source code and automatically create documentation
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto-documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm rebuild
    - run: npm install
    - run: npm run build-documentation
    - name: Commit files
      run: |
        git config --local user.email "andrew.kirby10@btinternet.com"
        git config --local user.name "AndrewKirby1"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
        github_token: d5394d94582e55bbf0fca5a0395d36763de44d65
        branch: ${{ github.ref }}
