# This workflow will do a clean install of node dependencies, build the source code and automatically create documentation
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto-documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Build
    uses: andstor/jsdoc-action@v1
    with:
      source_dir: ./components
      recurse: true
      output_dir: ./docs
